### PR TITLE
Bug fix 01955

### PR DESCRIPTION
**Pull request by zebrawild**
problem in fr res

### CODE REVIEW

**Review by mudmin — COMMENTED** [review]
Thanks for this. Because of the way our updates are distributed, we don't directly merge the PR, but I appreciate the work. This will go out in 5.6.8

**Comment by mudmin** [comment]
The language fix will go out to new installs and can be updated via spice shaker and the menu patch will go out in the 5.6.8 update. Thanks for everything.

**Comment by zebrawild** [comment]
You are welcome …Next time, I’ll propose à new plugin to switch the language from à menuset. Is there another branch / repository for this kind of Pull request ?David L.Le 3 mars 2024 à 17:02, mudmin ***@***.***> a écrit :﻿
The language fix will go out to new installs and can be updated via spice shaker and the menu patch will go out in the 5.6.8 update. Thanks for everything.

**Comment by mudmin** [comment]
Generally speaking, those things either come in on the discord server or bugs.userspice.com  Because of the way our patch system works, every update has to be hashed and stored in the database for an extra factor of authentication. It's how we can prove that the code has not been changed without our knowledge. So, if I push a PR, it actually breaks the download.  All plugins and system updates are hashed and then only the final code gets sent to this repo after it passes the "bleeding edge" testing. It's a little weird, but it works really well for those one click updates.

**Pull request closed without merging**
